name: LearnXtraChild
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.6.2

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.0.0
  intl: ^0.19.0
  fluttertoast: ^8.2.0
  flutter_launcher_icons: ^0.14.4
  device_info_plus: ^11.4.0
  permission_handler: ^12.0.1
  system_alert_window: ^2.0.7
  local_auth: ^2.1.0
  timer_count_down: ^2.2.2
  kiosk_mode: ^0.7.0
  lottie: ^3.3.0
  get: ^4.7.3
  http: ^1.6.0
  fl_chart: ^0.68.0
  url_launcher: ^6.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter_launcher_icons:
  android: "ic_launcher"
  ios: true
  image_path: "assets/images/ic_launcher.png"

flutter:
  uses-material-design: true

  assets:
    - assets/svg/
    - assets/images/
    - assets/lottie/

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700